version: '2.3'

services:
  statping:
    container_name: statping
    image: dockerhub.qingcloud.com/statping/statping:0.0.3
    restart: always
    volumes:
      - ./app:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8080:8080

